INSERT INTO gnnationhub.quartiers
(quartiers.commune_id, nom, code, est_actif, cree_par, modifie_par, created_at, updated_at)
VALUES
-- Commune 1 : Dixinn
    (1, "Kénien", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia 3", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia Chateau d'Eau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia Minière 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia Minière 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia Minière Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Hafia Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Centre 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Centre 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Gare Rails", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Gare", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Dixinn Port", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Camayenne", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Landreah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Cameroun", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Belle-vue école", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Belle Vue Marché 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Belle Vue Marché 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (1, "Minière Cité", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 2 : Kaloum
    (2, "Coronthie 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Coronthie 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Sandervalia", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Tombo", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Manquepas", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Boulbinet", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Sans Fil", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Teminetaye", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Almamya 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Almamya 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (2, "Kouléwondy", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 3 : Matam
    (3, "Matam", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Matam Lido", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Matam Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Bonfi", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Bonfi Routière", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Bonfi Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Hermakonon", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Hermakonon Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Touguiwondy", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Carrière Cité", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Carrière Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Madina Cité", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Madina Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Madina Ecole", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Madina Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Madina Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Lanseboundji", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Boussoura", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Coléyah CIté", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Coléyah Imprimerie", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Coléyah Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Coléyah Domino", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Mafanco", 'QUA', 1, 1, 1, NOW(), NOW()),
    (3, "Mafanco Centre", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 4 : Matoto
    (4, "Wanindara Dispensaire", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Sangoyah Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Sangoyah Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Kissosso", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Kissosso Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Simbaya 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Simbaya 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Simbaya Ecole", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Matoto Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Matoto Khabitaya", 'QUA', 1, 1, 1, NOW(), NOW()),
    (4, "Matoto Marché", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 5 : Ratoma
    (5, "Bambeto", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Nassouroulaye", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Kaporo Rails", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Kaporo Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "koloma Soloprimo", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Hamdallaye 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Hamdallaye Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Ratoma Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Ratoma Dispensaire", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Kipé", 'QUA', 1, 1, 1, NOW(), NOW()),
    (5, "Taouyah", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 6 : Gbessia
    (6, "Hamdallaye 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Koloma 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Koloma 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Yimbaya Tannerie", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Yimbaya Ecole", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Yimbaya Port", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Yimbaya Permanence", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Simbaya 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dar-Es-Salam 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dar-Es-Salam 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Behanzin", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Port 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Port 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Cité 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Cité 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Cité 3", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Ecole", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Gbéssia Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Cité de l'air", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Tanènè Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Tanènè Mosquée", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dabondy 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dabondy 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dabondy 3", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dabondy Ecole", 'QUA', 1, 1, 1, NOW(), NOW()),
    (6, "Dabondy Rails", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 7 : Tombolia
    (7, "Tombolia", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Tombolia Cité", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Tombolia Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Tombolia Plateau 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Tombolia Plateau 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Tombolia Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Cimenterie", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Dabompa Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Dabompa Plateau 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Dabompa Plateau 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Dabompa village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Enta Fassa", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Enta Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Enta Marché 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Enta Marché 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Lansanayah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Lansanayah Barrage", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Lansanayah Tâkoui", 'QUA', 1, 1, 1, NOW(), NOW()),
    (7, "Prince", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 8 : Lambanyi
    (8, "Lambanyi", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Waréah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Wanindara", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Wanindara Rails", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Simbaya Gare", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Bantounka 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Bantounka 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Nongo Morykanteya", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Nongo Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Nongo Kiroty", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Nongo Taady", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Yembeya", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Tanènè Marché", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Soumabossia 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Soumabossia 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (8, "Petit Simbaya", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 9 : Sonfonia
    (9, "Sonfonia centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Sonfonia Gare 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Sonfonia Radar", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Sonfonia Casse", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Yattaya Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Yattaya Fossidet", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Samatran Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Tamouyah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Kobayah Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Kobayah Rails", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Kobayah Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Kobayah Kinifi", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Foula Madina", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Barkayanka 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (9, "Baguisanayah", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 10 : Kagbèlen
    (10, "Ansoumanyah Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Ansoumania Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Tobolon 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Tobolon 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Dondolikhouré", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Kagbélen Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Kagbélen plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Baillobayah Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Baillobayah Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Keitaya", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Fofomèrè", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Samatran Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Tangan", 'QUA', 1, 1, 1, NOW(), NOW()),
    (10, "Kirikiran", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 11 : Sanoyah
    (11, "Sanoyah km36", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Sanoyah Rails Dispensaire", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Sanoyah Rails Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Kountiah Nord", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Kountiah Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Fassiah Centre", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Fassiah Textile", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "Kalokhoyah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "CBA Nord", 'QUA', 1, 1, 1, NOW(), NOW()),
    (11, "CBA Sud", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 12 : Kassa
    (12, "Kassa", 'QUA', 1, 1, 1, NOW(), NOW()),
    (12, "Fotoba", 'QUA', 1, 1, 1, NOW(), NOW()),


-- Commune 13 : Manéah
    (13, "Friguiady Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Friguiady Nord", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Gomboyah Village", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Gomboyah Nord", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Hermakono", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Tanènè 1", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Tanènè 2", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Bambayah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Kassognah", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Bentourayah Plateau", 'QUA', 1, 1, 1, NOW(), NOW()),
    (13, "Bentourayah Village", 'QUA', 1, 1, 1, NOW(), NOW());
